export type { FunctionNode } from "./function/function-node";
export { isFunctionNode } from "./function/is-function-node";
export { bindsName } from "./name/binds-name";
export { exportedName } from "./name/exported-name";
export { identifierName } from "./name/identifier-name";
export { staticKey } from "./name/static-key";
export { staticString } from "./name/static-string";
export { staticTextMatches } from "./name/static-text-matches";
export { typeReferenceName } from "./name/type-reference-name";
export { endOf } from "./range/end-of";
export type { Ranged } from "./range/ranged";
export { startOf } from "./range/start-of";
export type { IdentifierNode } from "./scope/identifier-node";
export { resolveVariable } from "./scope/resolve-variable";
export { areIdenticalSafeExpressions } from "./shape/are-identical-safe-expressions";
export { isCopyableReference } from "./shape/is-copyable-reference";
export { isCopyableReferenceTo } from "./shape/is-copyable-reference-to";
export { isSideEffectFree } from "./shape/is-side-effect-free";
export { sameLiteral } from "./shape/same-literal";
export { sameSafeShape } from "./shape/same-safe-shape";
export { containsNodeType } from "./traverse/contains-node-type";
export { isNode } from "./traverse/is-node";
export { traverse } from "./traverse/traverse";
export { unwrapAwaitedExpression } from "./unwrap/unwrap-awaited-expression";
export { unwrapExpression } from "./unwrap/unwrap-expression";
