export const DEFAULT_EXCEPTION_NAMES = [
	"BadGatewayException",
	"BadRequestException",
	"ConflictException",
	"ForbiddenException",
	"GatewayTimeoutException",
	"GoneException",
	"HttpException",
	"HttpVersionNotSupportedException",
	"ImATeapotException",
	"InternalServerErrorException",
	"MethodNotAllowedException",
	"MisdirectedException",
	"NotAcceptableException",
	"NotFoundException",
	"NotImplementedException",
	"PayloadTooLargeException",
	"PreconditionFailedException",
	"RequestTimeoutException",
	"ServiceUnavailableException",
	"UnauthorizedException",
	"UnprocessableEntityException",
	"UnsupportedMediaTypeException"
] as const;
